name: vidtiktoks
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.8.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  firebase_database: ^10.2.3
  google_sign_in: ^5.2.3
  flutter_screenutil: ^5.4.1
  get: ^4.6.1
  get_storage: 2.0.3
  image_picker: ^0.8.4+4
  timeago: ^3.1.0
  video_compress: 3.1.1
  video_player: ^2.7.0

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
